# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/*.tsx"
    - "!**/*.ts"
    - "!**/*.js"
    - "!**/*.svg"
chat:
  auto_reply: true
