// Package labelgen produces DNS-safe Agent Network subdomain labels.
//
// The wordlist below is a curated subset drawn from public-domain
// nature / common-noun pools (e.g. EFF's diceware lists). Every entry
// is lowercase ASCII, 4–12 chars, no hyphens, no digits, and was
// hand-checked to avoid offensive, brand, or region-specific terms.
package labelgen

// words is the pool PickUnique selects from. The slice is intentionally
// not sorted — random picks distribute across the list naturally.
var words = []string{
	"acorn", "adobe", "agate", "alder", "almond", "alpine", "amber", "amethyst",
	"anchor", "antler", "apple", "apricot", "arcade", "arctic", "arrow", "ashen",
	"aspen", "atlas", "atom", "aurora", "autumn", "azure",
	"badger", "bamboo", "banana", "banjo", "barley", "barn", "basalt", "basil",
	"basin", "bayou", "beach", "beacon", "beaver", "beech", "beetle", "berry",
	"birch", "bison", "blossom", "blue", "bobcat", "bonsai", "boulder", "branch",
	"brass", "breeze", "bridge", "bright", "brook", "broom", "brown", "buffalo",
	"bumble", "burrow", "butter", "button",
	"cabin", "cactus", "calm", "camel", "campfire", "canary", "candle", "canoe",
	"canyon", "cardinal", "carrot", "cascade", "castle", "cedar", "celery", "cello",
	"cement", "cherry", "chestnut", "chime", "cinnamon", "cinder", "citron", "clay",
	"clear", "cliff", "clock", "cloud", "clover", "coast", "cobalt", "cobble",
	"cocoa", "coffee", "comet", "compass", "copper", "coral", "corner", "cosmos",
	"cotton", "cougar", "country", "coyote", "cove", "crane", "crater", "creek",
	"crescent", "crimson", "crocus", "crystal", "cypress",
	"daffodil", "dahlia", "daisy", "dawn", "deer", "delta", "denim", "desert",
	"dewdrop", "diamond", "dolphin", "doodle", "dove", "dragon", "drift", "drop",
	"dune", "dusk", "dusty",
	"eagle", "earth", "echo", "elder", "elkhorn", "ember", "emerald", "emperor",
	"evergreen", "evening",
	"falcon", "fawn", "feather", "fern", "fiddle", "field", "fiesta", "finch",
	"firepit", "firefly", "fjord", "flame", "flax", "fleece", "flint", "floral",
	"flower", "flute", "foal", "foggy", "forest", "fountain", "foxglove", "fresh",
	"frost", "fuchsia", "fudge",
	"gable", "galaxy", "garden", "garnet", "gazelle", "geode", "geyser", "ginger",
	"glacier", "glade", "glass", "glow", "gold", "goose", "gorge", "gourd",
	"granite", "grape", "grass", "gravel", "grayling", "greenery", "grizzly", "grove",
	"gull", "gumdrop", "gust",
	"hammock", "harbor", "harvest", "hawk", "hazel", "heather", "hedge", "heron",
	"hibiscus", "hickory", "hideaway", "highland", "hill", "hive", "hollow", "honey",
	"hopper", "horizon", "hummingbird", "husky",
	"iceberg", "indigo", "iris", "island", "ivory", "ivybush",
	"jade", "jasmine", "jasper", "jaybird", "jelly", "jewel", "jonquil", "journey",
	"juniper", "jupiter", "jute",
	"kale", "kangaroo", "kayak", "kelp", "kestrel", "kettle", "khaki", "kindling",
	"kingfisher", "kiwi", "knapweed", "koala",
	"lagoon", "lake", "lantern", "larch", "lark", "laurel", "lava", "lavender",
	"leaf", "lemon", "lichen", "light", "lilac", "lily", "lime", "limestone",
	"linden", "linen", "lion", "lobster", "locust", "loon", "lotus", "lumber",
	"lunar", "lupine", "lynx",
	"madrone", "magenta", "magnolia", "mahogany", "mallow", "mango", "manor", "maple",
	"marble", "marigold", "marina", "marlin", "marsh", "mauve", "meadow", "melody",
	"melon", "merlin", "metal", "midnight", "milk", "millet", "mineral", "mint",
	"mirror", "mist", "mitten", "molasses", "moon", "moose", "morning", "moss",
	"mountain", "mulberry", "muscat", "mustard",
	"narwhal", "navy", "nectar", "needle", "nest", "nettle", "newt", "nightfall",
	"noon", "nook", "north", "nova", "nutmeg",
	"oaken", "oasis", "oatmeal", "ocean", "ochre", "octagon", "olive", "onyx",
	"opal", "orange", "orbit", "orchard", "orchid", "oregano", "orion", "osprey",
	"otter", "outpost", "owlet", "oyster",
	"painter", "palace", "palm", "pansy", "panther", "papaya", "paprika", "parsley",
	"partridge", "passage", "pastel", "patio", "peach", "peacock", "pear", "pearl",
	"pebble", "pecan", "pelican", "penguin", "peony", "pepper", "perch", "peridot",
	"pewter", "phoenix", "pier", "pillar", "pine", "pineapple", "pinto", "piper",
	"pistachio", "plain", "planet", "plateau", "platinum", "plum", "plume", "polar",
	"pollen", "pond", "poplar", "poppy", "porcelain", "portal", "portrait", "potato",
	"prairie", "primrose", "prism", "puffin", "pumpkin",
	"quail", "quartz", "quaver", "quill", "quince", "quinoa",
	"rabbit", "raccoon", "radish", "rain", "rainbow", "raindrop", "rapids", "raspberry",
	"raven", "ravine", "redwood", "reed", "reef", "ridge", "river", "robin",
	"rocket", "rubyred", "rose", "rosemary", "rosewood", "ruffle", "rugby", "russet",
	"rustic", "ryefield",
	"saffron", "sage", "salmon", "sand", "sandstone", "sapphire", "savanna", "scarlet",
	"scout", "seal", "season", "seaweed", "sequoia", "shadow", "shamrock", "shell",
	"sherbet", "shore", "silver", "siskin", "skybloom", "skyline", "sleet", "smoke",
	"snail", "snapdragon", "snow", "snowflake", "snowy", "solar", "song", "sonic",
	"sorrel", "south", "sparkle", "sparrow", "spice", "spider", "spinach", "spire",
	"spring", "sprout", "spruce", "squirrel", "starfish", "starlight", "stoat", "stone",
	"stork", "storm", "stream", "studio", "summer", "sunbeam", "sundew", "sunny",
	"sunrise", "sunset", "swallow", "swan", "sweet", "sycamore",
	"tangelo", "tangerine", "tansy", "taupe", "teak", "teal", "thicket", "thistle",
	"thrush", "thunder", "tide", "tiger", "tinder", "topaz", "torch", "tortoise",
	"tower", "trail", "tranquil", "tundra", "tulip", "turquoise", "turtle", "twig",
	"twilight",
	"umber", "uplands",
	"valley", "vanilla", "velvet", "venus", "verdant", "verdigris", "vermillion", "violet",
	"vista", "vivid", "volcano", "vortex",
	"walnut", "warbler", "watercress", "waterfall", "wave", "waxwing", "weasel", "westwind",
	"whale", "whisker", "whisper", "wicker", "wildwood", "willow", "winter", "wisp",
	"wisteria", "wolf", "wombat", "woodland", "woolly", "wren", "wreath",
	"yarrow", "yellow", "yewtree", "yodel",
	"zebra", "zenith", "zephyr", "zinnia",
	"alabaster", "alfalfa", "almanac", "anise", "antelope", "arbor", "arena", "armadillo",
	"avocet", "azalea", "balsam", "bayou", "beacon", "blizzard", "bluebell", "bluebird",
	"bluejay", "bobolink", "borage", "boreal", "buckeye", "buckthorn", "buttercup",
	"cabana", "calico", "canopy", "caraway", "cardamom", "cattail", "celadon", "centaur",
	"chambray", "chamois", "champlain", "chestnuts", "chickadee", "chinook", "chipmunk", "cinnabar",
	"cirrus", "citrine", "clematis", "copperhead",
	"crocodile", "currant", "cuttlebone", "daffy", "dapple", "delphinium", "dervish", "diamondback",
	"dogwood", "dolphins", "dragonfly", "driftwood", "dusk", "dustpan", "ebony", "edelweiss",
	"emperor", "endive", "estuary", "everglade", "fairway", "feldspar", "fennel", "fieldstone",
	"firebrand", "firefly", "fireweed", "firework", "flagstone", "fossil", "frostbite", "galleon",
	"gardener", "geranium", "gingko", "ginseng", "goldfish", "goldfinch", "goldenrod", "graphite",
	"greenfinch", "guppy", "haiku", "halibut", "hammerhead", "harbinger", "harvest", "hatchling",
	"havana", "hawthorn", "hazelnut", "heartwood", "henna", "heron", "highrise", "homestead",
	"honeycomb", "honeydew", "horseshoe", "hyacinth", "iceland", "icicle", "indigobird", "ironwood",
	"jacaranda", "jamboree", "javelina", "jellyfish", "junebug", "kaleido", "kayaker", "kerchief",
	"keystone", "kingdom", "labrador", "lacewing", "ladybug", "lakeside", "lamplight", "leopard",
	"lighthouse", "lilypad", "lullaby", "magnet", "mahonia", "mandolin", "manzanita", "maraschino",
	"mariner", "marsupial", "mastodon", "matterhorn", "mayflower", "mayfly", "meadowlark", "merlot",
	"meteor", "midshipman", "millpond", "mimosa", "minnow", "mockingbird", "molten", "monarch",
	"monsoon", "moondust", "moonlight", "moorland", "morning", "mossland", "mountain", "mulch",
	"narcissus", "nautilus", "nettlebush", "northstar", "nuthatch", "obsidian", "okra", "olivine",
	"opalescent", "orchidea", "orchard", "ornament", "outrigger", "oxalis", "paddler", "paintbrush",
	"papyrus", "paradise", "pasture", "patchwork", "pathway", "peridot", "periwinkle", "petalbloom",
	"petrel", "petunia", "phlox", "pikeperch", "pinecone", "pioneer", "pipevine", "platypus",
	"pomelo", "pondweed", "porpoise", "powder", "promise", "puddle", "pumice", "puzzle",
	"quetzal", "quicksilver", "racoon", "ragwort", "rainforest", "ramble", "rapid", "rascal",
	"raspberry", "redbud", "redfern", "redpoll", "reedling", "ringtail", "riverbed", "riverbird",
	"riverstone", "rockcress", "roebuck", "rosebay", "rosehip", "rosemary", "rowan", "rumble",
	"runaway", "rustler", "sagebrush", "sailcloth", "salamander", "salsify", "samphire", "sandbar",
	"sanddollar", "sandpiper", "santolina", "sapodilla", "sassafras", "scallion", "schooner", "seafoam",
	"seafrost", "seagrass", "seahorse", "seaport", "seashell", "seaspray", "shamble", "shimmer",
	"shoreline", "silkmoth", "silverfox", "skylark", "snapdragon", "snowberry", "snowdrop", "snowfall",
	"snowmelt", "softwood", "songbird", "sorghum", "southwind", "speedwell", "spinnaker", "spruce",
	"starlight", "starling", "stormcloud", "summit", "sundance", "sundew", "sundial", "sunflower",
	"surface", "swallowtail", "sweetcorn", "sycamore", "tabletop", "tamarack", "tamarind", "tangerine",
	"tarragon", "telescope", "thicket", "thrasher", "thunder", "thyme", "tideline", "timberland",
	"tinderbox", "topiary", "torchwood", "totem", "tradewind", "treasure", "tremolo", "trinket",
	"trumpetvine", "tugboat", "tundra", "turnstone", "underbrush", "vagabond", "valerian", "vanilla",
	"velveteen", "vermilion", "vinca", "vineyard", "violet", "voyager", "wagonwheel", "walnutwood",
	"watermark", "watershed", "waterway", "wavefront", "westerly", "whaleback", "whetstone", "wicker",
	"wildbloom", "wildflower", "wilderness", "windsong", "windward", "winterberry", "woodbine", "woodfern",
	"woodland", "woodthrush", "woolgrass", "yellowfin", "zenithal", "zucchini",
}
