// Code generated by libopenapi generator/golang. DO NOT EDIT.

package apiv1alpha1

import "time"

// CountryCode 2-letter ISO 3166-1 alpha-2 code that represents the country.
// CountryCode example value is defined in the OpenAPI schema.
type CountryCode string

// CityName Commonly used English name of the city.
// CityName example value is defined in the OpenAPI schema.
type CityName string

// Country Describe country geographical location information.
type Country struct {
	// CountryName Commonly used English name of the country.
	// CountryName example value is defined in the OpenAPI schema.
	CountryName string      `json:"country_name"`
	CountryCode CountryCode `json:"country_code"`
}

// City Describe city geographical location information.
type City struct {
	// GeonameId Integer ID of the record in GeoNames database.
	// GeonameId example value is defined in the OpenAPI schema.
	GeonameId int `json:"geoname_id"`
	// CityName Commonly used English name of the city.
	// CityName example value is defined in the OpenAPI schema.
	CityName string `json:"city_name"`
}

// ErrorResponse Standard error response. Note: The exact structure of this error response is inferred from `util.WriteErrorResponse` and `util.WriteError` usage in the provided Go code, as a specific Go struct for errors was not provided.
type ErrorResponse struct {
	// Message A human-readable error message.
	// Message example value is defined in the OpenAPI schema.
	Message *string `json:"message,omitempty"`
}

// GroupMinimumIssued How the group was issued (api, integration, jwt).
// GroupMinimumIssued example value is defined in the OpenAPI schema.
type GroupMinimumIssued string

const (
	GroupMinimumIssuedAPI         GroupMinimumIssued = "api"
	GroupMinimumIssuedIntegration GroupMinimumIssued = "integration"
	GroupMinimumIssuedJWT         GroupMinimumIssued = "jwt"
)

type GroupMinimum struct {
	// Id Group ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Group Name identifier.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// PeersCount Count of peers associated to the group.
	// PeersCount example value is defined in the OpenAPI schema.
	PeersCount int `json:"peers_count"`
	// ResourcesCount Count of resources associated to the group.
	// ResourcesCount example value is defined in the OpenAPI schema.
	ResourcesCount int `json:"resources_count"`
	// Issued How the group was issued (api, integration, jwt).
	// Issued example value is defined in the OpenAPI schema.
	Issued *GroupMinimumIssued `json:"issued,omitempty"`
}

type PeerRequest struct {
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// SshEnabled example value is defined in the OpenAPI schema.
	SshEnabled bool `json:"ssh_enabled"`
	// LoginExpirationEnabled example value is defined in the OpenAPI schema.
	LoginExpirationEnabled bool `json:"login_expiration_enabled"`
	// InactivityExpirationEnabled example value is defined in the OpenAPI schema.
	InactivityExpirationEnabled bool `json:"inactivity_expiration_enabled"`
	// ApprovalRequired (Cloud only) Indicates whether peer needs approval.
	// ApprovalRequired example value is defined in the OpenAPI schema.
	ApprovalRequired *bool `json:"approval_required,omitempty"`
	// Ip Peer's IP address.
	// Ip example value is defined in the OpenAPI schema.
	Ip *string `json:"ip,omitempty"`
	// Ipv6 Peer's IPv6 overlay address. Omitted if IPv6 is not enabled for the account.
	// Ipv6 example value is defined in the OpenAPI schema.
	Ipv6 *string `json:"ipv6,omitempty"`
}

// PeerAllOf2GroupsItemIssued How the group was issued (api, integration, jwt).
// PeerAllOf2GroupsItemIssued example value is defined in the OpenAPI schema.
type PeerAllOf2GroupsItemIssued string

const (
	PeerAllOf2GroupsItemIssuedAPI         PeerAllOf2GroupsItemIssued = "api"
	PeerAllOf2GroupsItemIssuedIntegration PeerAllOf2GroupsItemIssued = "integration"
	PeerAllOf2GroupsItemIssuedJWT         PeerAllOf2GroupsItemIssued = "jwt"
)

type PeerAllOf2GroupsItem struct {
	// Id Group ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Group Name identifier.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// PeersCount Count of peers associated to the group.
	// PeersCount example value is defined in the OpenAPI schema.
	PeersCount int `json:"peers_count"`
	// ResourcesCount Count of resources associated to the group.
	// ResourcesCount example value is defined in the OpenAPI schema.
	ResourcesCount int `json:"resources_count"`
	// Issued How the group was issued (api, integration, jwt).
	// Issued example value is defined in the OpenAPI schema.
	Issued *PeerAllOf2GroupsItemIssued `json:"issued,omitempty"`
}

type PeerAllOf2LocalFlags struct {
	// RosenpassEnabled Indicates whether Rosenpass is enabled on this peer.
	// RosenpassEnabled example value is defined in the OpenAPI schema.
	RosenpassEnabled *bool `json:"rosenpass_enabled,omitempty"`
	// RosenpassPermissive Indicates whether Rosenpass is in permissive mode or not.
	// RosenpassPermissive example value is defined in the OpenAPI schema.
	RosenpassPermissive *bool `json:"rosenpass_permissive,omitempty"`
	// ServerSshAllowed Indicates whether SSH access this peer is allowed or not.
	// ServerSshAllowed example value is defined in the OpenAPI schema.
	ServerSshAllowed *bool `json:"server_ssh_allowed,omitempty"`
	// RemoteJobsAllowed Indicates whether the peer has opted into management-requested remote jobs (e.g. debug bundles).
	// RemoteJobsAllowed example value is defined in the OpenAPI schema.
	RemoteJobsAllowed *bool `json:"remote_jobs_allowed,omitempty"`
	// DisableClientRoutes Indicates whether client routes are disabled on this peer or not.
	// DisableClientRoutes example value is defined in the OpenAPI schema.
	DisableClientRoutes *bool `json:"disable_client_routes,omitempty"`
	// DisableServerRoutes Indicates whether server routes are disabled on this peer or not.
	// DisableServerRoutes example value is defined in the OpenAPI schema.
	DisableServerRoutes *bool `json:"disable_server_routes,omitempty"`
	// DisableDns Indicates whether DNS management is disabled on this peer or not.
	// DisableDns example value is defined in the OpenAPI schema.
	DisableDns *bool `json:"disable_dns,omitempty"`
	// DisableFirewall Indicates whether firewall management is disabled on this peer or not.
	// DisableFirewall example value is defined in the OpenAPI schema.
	DisableFirewall *bool `json:"disable_firewall,omitempty"`
	// BlockLanAccess Indicates whether LAN access is blocked on this peer when used as a routing peer.
	// BlockLanAccess example value is defined in the OpenAPI schema.
	BlockLanAccess *bool `json:"block_lan_access,omitempty"`
	// BlockInbound Indicates whether inbound traffic is blocked on this peer.
	// BlockInbound example value is defined in the OpenAPI schema.
	BlockInbound *bool `json:"block_inbound,omitempty"`
	// LazyConnectionEnabled Indicates whether lazy connection is enabled on this peer.
	// LazyConnectionEnabled example value is defined in the OpenAPI schema.
	LazyConnectionEnabled *bool `json:"lazy_connection_enabled,omitempty"`
}

type Peer struct {
	// Id Peer ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Peer's hostname.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// CreatedAt Peer creation date (UTC).
	// CreatedAt example value is defined in the OpenAPI schema.
	CreatedAt time.Time `json:"created_at"`
	// Ip Peer's IP address.
	// Ip example value is defined in the OpenAPI schema.
	Ip string `json:"ip"`
	// Ipv6 Peer's IPv6 overlay address.
	// Ipv6 example value is defined in the OpenAPI schema.
	Ipv6 *string `json:"ipv6,omitempty"`
	// ConnectionIp Peer's public connection IP address.
	// ConnectionIp example value is defined in the OpenAPI schema.
	ConnectionIp string `json:"connection_ip"`
	// Connected Peer to Management connection status.
	// Connected example value is defined in the OpenAPI schema.
	Connected bool `json:"connected"`
	// LastSeen Last time peer connected to Netbird's management service.
	// LastSeen example value is defined in the OpenAPI schema.
	LastSeen time.Time `json:"last_seen"`
	// Os Peer's operating system and version.
	// Os example value is defined in the OpenAPI schema.
	Os string `json:"os"`
	// KernelVersion Peer's operating system kernel version.
	// KernelVersion example value is defined in the OpenAPI schema.
	KernelVersion string `json:"kernel_version"`
	// GeonameId Unique identifier from the GeoNames database for a specific geographical location.
	// GeonameId example value is defined in the OpenAPI schema.
	GeonameId int `json:"geoname_id"`
	// Version Peer's daemon or cli version.
	// Version example value is defined in the OpenAPI schema.
	Version string `json:"version"`
	// Groups Groups that the peer belongs to.
	Groups []PeerAllOf2GroupsItem `json:"groups"`
	// SshEnabled Indicates whether SSH server is enabled on this peer.
	// SshEnabled example value is defined in the OpenAPI schema.
	SshEnabled bool `json:"ssh_enabled"`
	// UserId User ID of the user that enrolled this peer.
	// UserId example value is defined in the OpenAPI schema.
	UserId string `json:"user_id"`
	// Hostname Hostname of the machine.
	// Hostname example value is defined in the OpenAPI schema.
	Hostname string `json:"hostname"`
	// UiVersion Peer's desktop UI version.
	// UiVersion example value is defined in the OpenAPI schema.
	UiVersion string `json:"ui_version"`
	// DnsLabel Peer's DNS label is the parsed peer name for domain resolution. It is used to form an FQDN by appending the account's domain to the peer label. e.g. peer-dns-label.netbird.cloud.
	// DnsLabel example value is defined in the OpenAPI schema.
	DnsLabel string `json:"dns_label"`
	// LoginExpirationEnabled Indicates whether peer login expiration has been enabled or not.
	// LoginExpirationEnabled example value is defined in the OpenAPI schema.
	LoginExpirationEnabled bool `json:"login_expiration_enabled"`
	// LoginExpired Indicates whether peer's login expired or not.
	// LoginExpired example value is defined in the OpenAPI schema.
	LoginExpired bool `json:"login_expired"`
	// LastLogin Last time this peer performed log in (authentication). E.g., user authenticated.
	// LastLogin example value is defined in the OpenAPI schema.
	LastLogin time.Time `json:"last_login"`
	// InactivityExpirationEnabled Indicates whether peer inactivity expiration has been enabled or not.
	// InactivityExpirationEnabled example value is defined in the OpenAPI schema.
	InactivityExpirationEnabled bool `json:"inactivity_expiration_enabled"`
	// ApprovalRequired (Cloud only) Indicates whether peer needs approval.
	// ApprovalRequired example value is defined in the OpenAPI schema.
	ApprovalRequired bool `json:"approval_required"`
	// DisapprovalReason (Cloud only) Reason why the peer requires approval.
	DisapprovalReason *string `json:"disapproval_reason,omitempty"`
	// CountryCode 2-letter ISO 3166-1 alpha-2 code that represents the country.
	// CountryCode example value is defined in the OpenAPI schema.
	CountryCode string `json:"country_code"`
	// CityName Commonly used English name of the city.
	// CityName example value is defined in the OpenAPI schema.
	CityName string `json:"city_name"`
	// SerialNumber System serial number.
	// SerialNumber example value is defined in the OpenAPI schema.
	SerialNumber string `json:"serial_number"`
	// ExtraDnsLabels Extra DNS labels added to the peer.
	ExtraDnsLabels []string `json:"extra_dns_labels"`
	// Ephemeral Indicates whether the peer is ephemeral or not.
	// Ephemeral example value is defined in the OpenAPI schema.
	Ephemeral  bool                  `json:"ephemeral"`
	LocalFlags *PeerAllOf2LocalFlags `json:"local_flags,omitempty"`
}

// PeerBatchAllOf1AllOf2GroupsItemIssued How the group was issued (api, integration, jwt).
// PeerBatchAllOf1AllOf2GroupsItemIssued example value is defined in the OpenAPI schema.
type PeerBatchAllOf1AllOf2GroupsItemIssued string

const (
	PeerBatchAllOf1AllOf2GroupsItemIssuedAPI         PeerBatchAllOf1AllOf2GroupsItemIssued = "api"
	PeerBatchAllOf1AllOf2GroupsItemIssuedIntegration PeerBatchAllOf1AllOf2GroupsItemIssued = "integration"
	PeerBatchAllOf1AllOf2GroupsItemIssuedJWT         PeerBatchAllOf1AllOf2GroupsItemIssued = "jwt"
)

type PeerBatchAllOf1AllOf2GroupsItem struct {
	// Id Group ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Group Name identifier.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// PeersCount Count of peers associated to the group.
	// PeersCount example value is defined in the OpenAPI schema.
	PeersCount int `json:"peers_count"`
	// ResourcesCount Count of resources associated to the group.
	// ResourcesCount example value is defined in the OpenAPI schema.
	ResourcesCount int `json:"resources_count"`
	// Issued How the group was issued (api, integration, jwt).
	// Issued example value is defined in the OpenAPI schema.
	Issued *PeerBatchAllOf1AllOf2GroupsItemIssued `json:"issued,omitempty"`
}

type PeerBatchAllOf1AllOf2LocalFlags struct {
	// RosenpassEnabled Indicates whether Rosenpass is enabled on this peer.
	// RosenpassEnabled example value is defined in the OpenAPI schema.
	RosenpassEnabled *bool `json:"rosenpass_enabled,omitempty"`
	// RosenpassPermissive Indicates whether Rosenpass is in permissive mode or not.
	// RosenpassPermissive example value is defined in the OpenAPI schema.
	RosenpassPermissive *bool `json:"rosenpass_permissive,omitempty"`
	// ServerSshAllowed Indicates whether SSH access this peer is allowed or not.
	// ServerSshAllowed example value is defined in the OpenAPI schema.
	ServerSshAllowed *bool `json:"server_ssh_allowed,omitempty"`
	// RemoteJobsAllowed Indicates whether the peer has opted into management-requested remote jobs (e.g. debug bundles).
	// RemoteJobsAllowed example value is defined in the OpenAPI schema.
	RemoteJobsAllowed *bool `json:"remote_jobs_allowed,omitempty"`
	// DisableClientRoutes Indicates whether client routes are disabled on this peer or not.
	// DisableClientRoutes example value is defined in the OpenAPI schema.
	DisableClientRoutes *bool `json:"disable_client_routes,omitempty"`
	// DisableServerRoutes Indicates whether server routes are disabled on this peer or not.
	// DisableServerRoutes example value is defined in the OpenAPI schema.
	DisableServerRoutes *bool `json:"disable_server_routes,omitempty"`
	// DisableDns Indicates whether DNS management is disabled on this peer or not.
	// DisableDns example value is defined in the OpenAPI schema.
	DisableDns *bool `json:"disable_dns,omitempty"`
	// DisableFirewall Indicates whether firewall management is disabled on this peer or not.
	// DisableFirewall example value is defined in the OpenAPI schema.
	DisableFirewall *bool `json:"disable_firewall,omitempty"`
	// BlockLanAccess Indicates whether LAN access is blocked on this peer when used as a routing peer.
	// BlockLanAccess example value is defined in the OpenAPI schema.
	BlockLanAccess *bool `json:"block_lan_access,omitempty"`
	// BlockInbound Indicates whether inbound traffic is blocked on this peer.
	// BlockInbound example value is defined in the OpenAPI schema.
	BlockInbound *bool `json:"block_inbound,omitempty"`
	// LazyConnectionEnabled Indicates whether lazy connection is enabled on this peer.
	// LazyConnectionEnabled example value is defined in the OpenAPI schema.
	LazyConnectionEnabled *bool `json:"lazy_connection_enabled,omitempty"`
}

type PeerBatch struct {
	// Id Peer ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Peer's hostname.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
	// CreatedAt Peer creation date (UTC).
	// CreatedAt example value is defined in the OpenAPI schema.
	CreatedAt time.Time `json:"created_at"`
	// Ip Peer's IP address.
	// Ip example value is defined in the OpenAPI schema.
	Ip string `json:"ip"`
	// Ipv6 Peer's IPv6 overlay address.
	// Ipv6 example value is defined in the OpenAPI schema.
	Ipv6 *string `json:"ipv6,omitempty"`
	// ConnectionIp Peer's public connection IP address.
	// ConnectionIp example value is defined in the OpenAPI schema.
	ConnectionIp string `json:"connection_ip"`
	// Connected Peer to Management connection status.
	// Connected example value is defined in the OpenAPI schema.
	Connected bool `json:"connected"`
	// LastSeen Last time peer connected to Netbird's management service.
	// LastSeen example value is defined in the OpenAPI schema.
	LastSeen time.Time `json:"last_seen"`
	// Os Peer's operating system and version.
	// Os example value is defined in the OpenAPI schema.
	Os string `json:"os"`
	// KernelVersion Peer's operating system kernel version.
	// KernelVersion example value is defined in the OpenAPI schema.
	KernelVersion string `json:"kernel_version"`
	// GeonameId Unique identifier from the GeoNames database for a specific geographical location.
	// GeonameId example value is defined in the OpenAPI schema.
	GeonameId int `json:"geoname_id"`
	// Version Peer's daemon or cli version.
	// Version example value is defined in the OpenAPI schema.
	Version string `json:"version"`
	// Groups Groups that the peer belongs to.
	Groups []PeerBatchAllOf1AllOf2GroupsItem `json:"groups"`
	// SshEnabled Indicates whether SSH server is enabled on this peer.
	// SshEnabled example value is defined in the OpenAPI schema.
	SshEnabled bool `json:"ssh_enabled"`
	// UserId User ID of the user that enrolled this peer.
	// UserId example value is defined in the OpenAPI schema.
	UserId string `json:"user_id"`
	// Hostname Hostname of the machine.
	// Hostname example value is defined in the OpenAPI schema.
	Hostname string `json:"hostname"`
	// UiVersion Peer's desktop UI version.
	// UiVersion example value is defined in the OpenAPI schema.
	UiVersion string `json:"ui_version"`
	// DnsLabel Peer's DNS label is the parsed peer name for domain resolution. It is used to form an FQDN by appending the account's domain to the peer label. e.g. peer-dns-label.netbird.cloud.
	// DnsLabel example value is defined in the OpenAPI schema.
	DnsLabel string `json:"dns_label"`
	// LoginExpirationEnabled Indicates whether peer login expiration has been enabled or not.
	// LoginExpirationEnabled example value is defined in the OpenAPI schema.
	LoginExpirationEnabled bool `json:"login_expiration_enabled"`
	// LoginExpired Indicates whether peer's login expired or not.
	// LoginExpired example value is defined in the OpenAPI schema.
	LoginExpired bool `json:"login_expired"`
	// LastLogin Last time this peer performed log in (authentication). E.g., user authenticated.
	// LastLogin example value is defined in the OpenAPI schema.
	LastLogin time.Time `json:"last_login"`
	// InactivityExpirationEnabled Indicates whether peer inactivity expiration has been enabled or not.
	// InactivityExpirationEnabled example value is defined in the OpenAPI schema.
	InactivityExpirationEnabled bool `json:"inactivity_expiration_enabled"`
	// ApprovalRequired (Cloud only) Indicates whether peer needs approval.
	// ApprovalRequired example value is defined in the OpenAPI schema.
	ApprovalRequired bool `json:"approval_required"`
	// DisapprovalReason (Cloud only) Reason why the peer requires approval.
	DisapprovalReason *string `json:"disapproval_reason,omitempty"`
	// CountryCode 2-letter ISO 3166-1 alpha-2 code that represents the country.
	// CountryCode example value is defined in the OpenAPI schema.
	CountryCode string `json:"country_code"`
	// CityName Commonly used English name of the city.
	// CityName example value is defined in the OpenAPI schema.
	CityName string `json:"city_name"`
	// SerialNumber System serial number.
	// SerialNumber example value is defined in the OpenAPI schema.
	SerialNumber string `json:"serial_number"`
	// ExtraDnsLabels Extra DNS labels added to the peer.
	ExtraDnsLabels []string `json:"extra_dns_labels"`
	// Ephemeral Indicates whether the peer is ephemeral or not.
	// Ephemeral example value is defined in the OpenAPI schema.
	Ephemeral  bool                             `json:"ephemeral"`
	LocalFlags *PeerBatchAllOf1AllOf2LocalFlags `json:"local_flags,omitempty"`
	// AccessiblePeersCount Number of accessible peers.
	// AccessiblePeersCount example value is defined in the OpenAPI schema.
	AccessiblePeersCount int `json:"accessible_peers_count"`
}

type PeerMinumum struct {
	// Id Peer ID.
	// Id example value is defined in the OpenAPI schema.
	Id string `json:"id"`
	// Name Peer's hostname.
	// Name example value is defined in the OpenAPI schema.
	Name string `json:"name"`
}
