// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v6.33.0
// source: proxy_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceUpdate_UpdateType int32

const (
	ServiceUpdate_CREATED ServiceUpdate_UpdateType = 0
	ServiceUpdate_UPDATED ServiceUpdate_UpdateType = 1
	ServiceUpdate_REMOVED ServiceUpdate_UpdateType = 2
)

// Enum value maps for ServiceUpdate_UpdateType.
var (
	ServiceUpdate_UpdateType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "REMOVED",
	}
	ServiceUpdate_UpdateType_value = map[string]int32{
		"CREATED": 0,
		"UPDATED": 1,
		"REMOVED": 2,
	}
)

func (x ServiceUpdate_UpdateType) Enum() *ServiceUpdate_UpdateType {
	p := new(ServiceUpdate_UpdateType)
	*p = x
	return p
}

func (x ServiceUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_service_proto_enumTypes[0].Descriptor()
}

func (ServiceUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_proxy_service_proto_enumTypes[0]
}

func (x ServiceUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceUpdate_UpdateType.Descriptor instead.
func (ServiceUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{5, 0}
}

// Messages FROM Proxy TO Management
type ProxyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ProxyMessage_Hello
	//	*ProxyMessage_RequestData
	Payload isProxyMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ProxyMessage) Reset() {
	*x = ProxyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMessage) ProtoMessage() {}

func (x *ProxyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMessage.ProtoReflect.Descriptor instead.
func (*ProxyMessage) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{0}
}

func (m *ProxyMessage) GetPayload() isProxyMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ProxyMessage) GetHello() *ProxyHello {
	if x, ok := x.GetPayload().(*ProxyMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ProxyMessage) GetRequestData() *ProxyRequestData {
	if x, ok := x.GetPayload().(*ProxyMessage_RequestData); ok {
		return x.RequestData
	}
	return nil
}

type isProxyMessage_Payload interface {
	isProxyMessage_Payload()
}

type ProxyMessage_Hello struct {
	Hello *ProxyHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // First message on connect
}

type ProxyMessage_RequestData struct {
	RequestData *ProxyRequestData `protobuf:"bytes,2,opt,name=request_data,json=requestData,proto3,oneof"` // Real-time access logs
}

func (*ProxyMessage_Hello) isProxyMessage_Payload() {}

func (*ProxyMessage_RequestData) isProxyMessage_Payload() {}

// Proxy identification on connect
type ProxyHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyId   string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Version   string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *ProxyHello) Reset() {
	*x = ProxyHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHello) ProtoMessage() {}

func (x *ProxyHello) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHello.ProtoReflect.Descriptor instead.
func (*ProxyHello) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyHello) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProxyHello) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Access log from proxy to management
type ProxyRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	ResponseCode  int32                  `protobuf:"varint,7,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	SourceIp      string                 `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	AuthMechanism string                 `protobuf:"bytes,9,opt,name=auth_mechanism,json=authMechanism,proto3" json:"auth_mechanism,omitempty"`
	UserId        string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthSuccess   bool                   `protobuf:"varint,11,opt,name=auth_success,json=authSuccess,proto3" json:"auth_success,omitempty"`
}

func (x *ProxyRequestData) Reset() {
	*x = ProxyRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequestData) ProtoMessage() {}

func (x *ProxyRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequestData.ProtoReflect.Descriptor instead.
func (*ProxyRequestData) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyRequestData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ProxyRequestData) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ProxyRequestData) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyRequestData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyRequestData) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ProxyRequestData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequestData) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *ProxyRequestData) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ProxyRequestData) GetAuthMechanism() string {
	if x != nil {
		return x.AuthMechanism
	}
	return ""
}

func (x *ProxyRequestData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProxyRequestData) GetAuthSuccess() bool {
	if x != nil {
		return x.AuthSuccess
	}
	return false
}

// Messages FROM Management TO Proxy
type ManagementMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ManagementMessage_Snapshot
	//	*ManagementMessage_Update
	Payload isManagementMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ManagementMessage) Reset() {
	*x = ManagementMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagementMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagementMessage) ProtoMessage() {}

func (x *ManagementMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagementMessage.ProtoReflect.Descriptor instead.
func (*ManagementMessage) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{3}
}

func (m *ManagementMessage) GetPayload() isManagementMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ManagementMessage) GetSnapshot() *ServicesSnapshot {
	if x, ok := x.GetPayload().(*ManagementMessage_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *ManagementMessage) GetUpdate() *ServiceUpdate {
	if x, ok := x.GetPayload().(*ManagementMessage_Update); ok {
		return x.Update
	}
	return nil
}

type isManagementMessage_Payload interface {
	isManagementMessage_Payload()
}

type ManagementMessage_Snapshot struct {
	Snapshot *ServicesSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // Full snapshot on initial connect
}

type ManagementMessage_Update struct {
	Update *ServiceUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"` // Incremental service update
}

func (*ManagementMessage_Snapshot) isManagementMessage_Payload() {}

func (*ManagementMessage_Update) isManagementMessage_Payload() {}

// Full snapshot of all services for this proxy
type ServicesSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services  []*ExposedServiceConfig `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Timestamp *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ServicesSnapshot) Reset() {
	*x = ServicesSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesSnapshot) ProtoMessage() {}

func (x *ServicesSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesSnapshot.ProtoReflect.Descriptor instead.
func (*ServicesSnapshot) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServicesSnapshot) GetServices() []*ExposedServiceConfig {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ServicesSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Incremental service update
type ServiceUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ServiceUpdate_UpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=management.ServiceUpdate_UpdateType" json:"type,omitempty"`
	Service   *ExposedServiceConfig    `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                      // Set for CREATED and UPDATED
	ServiceId string                   `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // Service ID (always set)
}

func (x *ServiceUpdate) Reset() {
	*x = ServiceUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUpdate) ProtoMessage() {}

func (x *ServiceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUpdate.ProtoReflect.Descriptor instead.
func (*ServiceUpdate) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceUpdate) GetType() ServiceUpdate_UpdateType {
	if x != nil {
		return x.Type
	}
	return ServiceUpdate_CREATED
}

func (x *ServiceUpdate) GetService() *ExposedServiceConfig {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ServiceUpdate) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// Exposed service configuration
type ExposedServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain       string            `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	PathMappings map[string]string `protobuf:"bytes,3,rep,name=path_mappings,json=pathMappings,proto3" json:"path_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // path -> target
	SetupKey     string            `protobuf:"bytes,4,opt,name=setup_key,json=setupKey,proto3" json:"setup_key,omitempty"`
	Auth         *AuthConfig       `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *ExposedServiceConfig) Reset() {
	*x = ExposedServiceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExposedServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposedServiceConfig) ProtoMessage() {}

func (x *ExposedServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposedServiceConfig.ProtoReflect.Descriptor instead.
func (*ExposedServiceConfig) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExposedServiceConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExposedServiceConfig) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExposedServiceConfig) GetPathMappings() map[string]string {
	if x != nil {
		return x.PathMappings
	}
	return nil
}

func (x *ExposedServiceConfig) GetSetupKey() string {
	if x != nil {
		return x.SetupKey
	}
	return ""
}

func (x *ExposedServiceConfig) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

// Authentication configuration
type AuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AuthType:
	//
	//	*AuthConfig_BasicAuth
	//	*AuthConfig_PinAuth
	//	*AuthConfig_BearerAuth
	AuthType isAuthConfig_AuthType `protobuf_oneof:"auth_type"`
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{7}
}

func (m *AuthConfig) GetAuthType() isAuthConfig_AuthType {
	if m != nil {
		return m.AuthType
	}
	return nil
}

func (x *AuthConfig) GetBasicAuth() *BasicAuthConfig {
	if x, ok := x.GetAuthType().(*AuthConfig_BasicAuth); ok {
		return x.BasicAuth
	}
	return nil
}

func (x *AuthConfig) GetPinAuth() *PinAuthConfig {
	if x, ok := x.GetAuthType().(*AuthConfig_PinAuth); ok {
		return x.PinAuth
	}
	return nil
}

func (x *AuthConfig) GetBearerAuth() *BearerAuthConfig {
	if x, ok := x.GetAuthType().(*AuthConfig_BearerAuth); ok {
		return x.BearerAuth
	}
	return nil
}

type isAuthConfig_AuthType interface {
	isAuthConfig_AuthType()
}

type AuthConfig_BasicAuth struct {
	BasicAuth *BasicAuthConfig `protobuf:"bytes,1,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

type AuthConfig_PinAuth struct {
	PinAuth *PinAuthConfig `protobuf:"bytes,2,opt,name=pin_auth,json=pinAuth,proto3,oneof"`
}

type AuthConfig_BearerAuth struct {
	BearerAuth *BearerAuthConfig `protobuf:"bytes,3,opt,name=bearer_auth,json=bearerAuth,proto3,oneof"`
}

func (*AuthConfig_BasicAuth) isAuthConfig_AuthType() {}

func (*AuthConfig_PinAuth) isAuthConfig_AuthType() {}

func (*AuthConfig_BearerAuth) isAuthConfig_AuthType() {}

type BasicAuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BasicAuthConfig) Reset() {
	*x = BasicAuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuthConfig) ProtoMessage() {}

func (x *BasicAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuthConfig.ProtoReflect.Descriptor instead.
func (*BasicAuthConfig) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{8}
}

func (x *BasicAuthConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuthConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PinAuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pin    string `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Header string `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *PinAuthConfig) Reset() {
	*x = PinAuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinAuthConfig) ProtoMessage() {}

func (x *PinAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinAuthConfig.ProtoReflect.Descriptor instead.
func (*PinAuthConfig) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{9}
}

func (x *PinAuthConfig) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *PinAuthConfig) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type BearerAuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *BearerAuthConfig) Reset() {
	*x = BearerAuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BearerAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerAuthConfig) ProtoMessage() {}

func (x *BearerAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearerAuthConfig.ProtoReflect.Descriptor instead.
func (*BearerAuthConfig) Descriptor() ([]byte, []int) {
	return file_proxy_service_proto_rawDescGZIP(), []int{10}
}

func (x *BearerAuthConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_proxy_service_proto protoreflect.FileDescriptor

var file_proxy_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x41, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x7c, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0xf1, 0x02, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x70,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x70,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x63, 0x68, 0x61, 0x6e, 0x69,
	0x73, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x65,
	0x63, 0x68, 0x61, 0x6e, 0x69, 0x73, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x08, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0xd9, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3a,
	0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x70,
	0x6f, 0x73, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0a, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x22, 0xa1,
	0x02, 0x0a, 0x14, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x57, 0x0a, 0x0d, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x70, 0x61, 0x74, 0x68,
	0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x74, 0x75,
	0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x74,
	0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x61, 0x75, 0x74,
	0x68, 0x1a, 0x3f, 0x0a, 0x11, 0x50, 0x61, 0x74, 0x68, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xd0, 0x01, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x3c, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x36, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x07,
	0x70, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x0b, 0x62, 0x65, 0x61, 0x72, 0x65,
	0x72, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x65,
	0x61, 0x72, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x42, 0x0b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x39, 0x0a, 0x0d, 0x50, 0x69, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x70, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x42,
	0x65, 0x61, 0x72, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x32, 0x55, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1d, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proxy_service_proto_rawDescOnce sync.Once
	file_proxy_service_proto_rawDescData = file_proxy_service_proto_rawDesc
)

func file_proxy_service_proto_rawDescGZIP() []byte {
	file_proxy_service_proto_rawDescOnce.Do(func() {
		file_proxy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_service_proto_rawDescData)
	})
	return file_proxy_service_proto_rawDescData
}

var file_proxy_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proxy_service_proto_goTypes = []interface{}{
	(ServiceUpdate_UpdateType)(0), // 0: management.ServiceUpdate.UpdateType
	(*ProxyMessage)(nil),          // 1: management.ProxyMessage
	(*ProxyHello)(nil),            // 2: management.ProxyHello
	(*ProxyRequestData)(nil),      // 3: management.ProxyRequestData
	(*ManagementMessage)(nil),     // 4: management.ManagementMessage
	(*ServicesSnapshot)(nil),      // 5: management.ServicesSnapshot
	(*ServiceUpdate)(nil),         // 6: management.ServiceUpdate
	(*ExposedServiceConfig)(nil),  // 7: management.ExposedServiceConfig
	(*AuthConfig)(nil),            // 8: management.AuthConfig
	(*BasicAuthConfig)(nil),       // 9: management.BasicAuthConfig
	(*PinAuthConfig)(nil),         // 10: management.PinAuthConfig
	(*BearerAuthConfig)(nil),      // 11: management.BearerAuthConfig
	nil,                           // 12: management.ExposedServiceConfig.PathMappingsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proxy_service_proto_depIdxs = []int32{
	2,  // 0: management.ProxyMessage.hello:type_name -> management.ProxyHello
	3,  // 1: management.ProxyMessage.request_data:type_name -> management.ProxyRequestData
	13, // 2: management.ProxyHello.started_at:type_name -> google.protobuf.Timestamp
	13, // 3: management.ProxyRequestData.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 4: management.ManagementMessage.snapshot:type_name -> management.ServicesSnapshot
	6,  // 5: management.ManagementMessage.update:type_name -> management.ServiceUpdate
	7,  // 6: management.ServicesSnapshot.services:type_name -> management.ExposedServiceConfig
	13, // 7: management.ServicesSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 8: management.ServiceUpdate.type:type_name -> management.ServiceUpdate.UpdateType
	7,  // 9: management.ServiceUpdate.service:type_name -> management.ExposedServiceConfig
	12, // 10: management.ExposedServiceConfig.path_mappings:type_name -> management.ExposedServiceConfig.PathMappingsEntry
	8,  // 11: management.ExposedServiceConfig.auth:type_name -> management.AuthConfig
	9,  // 12: management.AuthConfig.basic_auth:type_name -> management.BasicAuthConfig
	10, // 13: management.AuthConfig.pin_auth:type_name -> management.PinAuthConfig
	11, // 14: management.AuthConfig.bearer_auth:type_name -> management.BearerAuthConfig
	1,  // 15: management.ProxyService.Stream:input_type -> management.ProxyMessage
	4,  // 16: management.ProxyService.Stream:output_type -> management.ManagementMessage
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proxy_service_proto_init() }
func file_proxy_service_proto_init() {
	if File_proxy_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxy_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagementMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExposedServiceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinAuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BearerAuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proxy_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProxyMessage_Hello)(nil),
		(*ProxyMessage_RequestData)(nil),
	}
	file_proxy_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ManagementMessage_Snapshot)(nil),
		(*ManagementMessage_Update)(nil),
	}
	file_proxy_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*AuthConfig_BasicAuth)(nil),
		(*AuthConfig_PinAuth)(nil),
		(*AuthConfig_BearerAuth)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxy_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_service_proto_goTypes,
		DependencyIndexes: file_proxy_service_proto_depIdxs,
		EnumInfos:         file_proxy_service_proto_enumTypes,
		MessageInfos:      file_proxy_service_proto_msgTypes,
	}.Build()
	File_proxy_service_proto = out.File
	file_proxy_service_proto_rawDesc = nil
	file_proxy_service_proto_goTypes = nil
	file_proxy_service_proto_depIdxs = nil
}
