-- +goose Up
SET LOCAL lock_timeout = '5s';
CREATE TABLE "accounts" ("id" text,"created_by" text,"created_at" timestamptz,"domain" text,"domain_category" text,"is_domain_primary_account" boolean,"network_identifier" text,"network_net" text,"network_net_v6" text,"network_dns" text,"network_serial" bigint,"dns_settings_disabled_management_groups" text,"settings_peer_login_expiration_enabled" boolean,"settings_peer_login_expiration" bigint,"settings_peer_inactivity_expiration_enabled" boolean,"settings_peer_inactivity_expiration" bigint,"settings_regular_users_view_blocked" boolean,"settings_groups_propagation_enabled" boolean,"settings_jwt_groups_enabled" boolean,"settings_jwt_groups_claim_name" text,"settings_jwt_allow_groups" text,"settings_routing_peer_dns_resolution_enabled" boolean,"settings_dns_domain" text,"settings_network_range" text,"settings_network_range_v6" text,"settings_peer_expose_enabled" boolean,"settings_peer_expose_groups" text,"settings_extra_peer_approval_enabled" boolean,"settings_extra_user_approval_required" boolean,"settings_extra_integrated_validator" text,"settings_extra_integrated_validator_groups" text,"settings_lazy_connection_enabled" boolean DEFAULT false,"settings_auto_update_version" text DEFAULT 'disabled',"settings_auto_update_always" boolean DEFAULT false,"settings_ipv6_enabled_groups" text,"settings_metrics_push_enabled" boolean DEFAULT false,"settings_agent_network_only" boolean DEFAULT false,"settings_dashboard_features" text,"settings_local_mfa_enabled" boolean,"reverse_proxy_free_domain_nonce" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_accounts_domain" ON "accounts" ("domain");
CREATE TABLE "setup_keys" ("id" text,"account_id" text,"key" text,"key_secret" text,"name" text,"type" text,"created_at" timestamptz,"expires_at" timestamptz,"updated_at" timestamptz,"revoked" boolean,"used_times" bigint,"last_used" timestamptz,"auto_groups" text,"usage_limit" bigint,"ephemeral" boolean,"allow_extra_dns_labels" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_setup_keys_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_setup_keys_key_secret" ON "setup_keys" ("key_secret");
CREATE INDEX IF NOT EXISTS "idx_setup_keys_account_id" ON "setup_keys" ("account_id");
CREATE TABLE "peers" ("id" text,"account_id" text,"key" text,"ip" text,"ipv6" text,"meta_hostname" text,"meta_go_os" text,"meta_kernel" text,"meta_core" text,"meta_platform" text,"meta_os" text,"meta_os_version" text,"meta_wt_version" text,"meta_ui_version" text,"meta_kernel_version" text,"meta_network_addresses" text,"meta_system_serial_number" text,"meta_system_product_name" text,"meta_system_manufacturer" text,"meta_environment" text,"meta_flags" text,"meta_files" text,"meta_capabilities" text,"meta_sync_message_version" bigint,"proxy_meta_embedded" boolean,"proxy_meta_cluster" text,"name" text,"dns_label" text,"peer_status_last_seen" timestamptz,"peer_status_session_started_at" bigint NOT NULL DEFAULT 0,"peer_status_connected" boolean,"peer_status_login_expired" boolean,"peer_status_requires_approval" boolean,"user_id" text,"ssh_key" text,"ssh_enabled" boolean,"login_expiration_enabled" boolean,"inactivity_expiration_enabled" boolean,"last_login" timestamptz,"created_at" timestamptz,"ephemeral" boolean,"location_connection_ip" text,"location_country_code" text,"location_city_name" text,"location_geo_name_id" bigint,"extra_dns_labels" text,"allow_extra_dns_labels" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_peers_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_peers_ephemeral" ON "peers" ("ephemeral");
CREATE INDEX IF NOT EXISTS "idx_peers_name" ON "peers" ("name");
CREATE INDEX IF NOT EXISTS "idx_peers_cluster" ON "peers" ("proxy_meta_cluster");
CREATE INDEX IF NOT EXISTS "idx_peers_embedded" ON "peers" ("proxy_meta_embedded");
CREATE INDEX IF NOT EXISTS "idx_peers_account_id" ON "peers" ("account_id");
CREATE TABLE "users" ("id" text,"account_id" text,"role" text,"is_service_user" boolean,"non_deletable" boolean,"service_user_name" text,"auto_groups" text,"blocked" boolean,"pending_approval" boolean,"last_login" timestamptz,"created_at" timestamptz,"issued" text DEFAULT 'api',"integration_ref_id" bigint,"integration_ref_integration_type" text,"name" text DEFAULT '',"email" text DEFAULT '',PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_users_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_users_account_id" ON "users" ("account_id");
CREATE TABLE "personal_access_tokens" ("id" text,"user_id" text,"name" text,"hashed_token" text,"expiration_date" timestamptz,"created_by" text,"created_at" timestamptz,"last_used" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "fk_users_pa_ts_g" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "idx_personal_access_tokens_user_id" ON "personal_access_tokens" ("user_id");
CREATE TABLE "proxy_access_tokens" ("id" text,"name" text,"hashed_token" varchar(255),"account_id" text,"expires_at" timestamptz,"created_by" text,"created_at" timestamptz,"last_used" timestamptz,"revoked" boolean,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_proxy_access_tokens_account_id" ON "proxy_access_tokens" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_proxy_access_tokens_hashed_token" ON "proxy_access_tokens" ("hashed_token");
CREATE TABLE "groups" ("id" text,"account_id" text,"public_id" text,"name" text,"issued" text,"resources" text,"integration_ref_id" bigint,"integration_ref_integration_type" text,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_groups_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_groups_account_id" ON "groups" ("account_id");
CREATE TABLE "group_peers" ("account_id" text,"group_id" text,"peer_id" text,PRIMARY KEY ("group_id","peer_id"),CONSTRAINT "fk_groups_group_peers" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "idx_group_peers_account_id" ON "group_peers" ("account_id");
CREATE TABLE "policies" ("id" text,"public_id" text,"account_id" text,"name" text,"description" text,"enabled" boolean,"source_posture_checks" text,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_policies" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_policies_public_id" ON "policies" ("public_id");
CREATE INDEX IF NOT EXISTS "idx_policies_account_id" ON "policies" ("account_id");
CREATE TABLE "policy_rules" ("id" text,"policy_id" text,"name" text,"description" text,"enabled" boolean,"action" text,"destinations" text,"destination_resource" text,"sources" text,"source_resource" text,"bidirectional" boolean,"protocol" text,"ports" text,"port_ranges" text,"authorized_groups" text,"authorized_user" text,PRIMARY KEY ("id"),CONSTRAINT "fk_policies_rules" FOREIGN KEY ("policy_id") REFERENCES "policies"("id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "idx_policy_rules_policy_id" ON "policy_rules" ("policy_id");
CREATE TABLE "routes" ("id" text,"account_id" text,"public_id" text,"network" text,"domains" text,"keep_route" boolean,"net_id" text,"description" text,"peer" text,"peer_groups" text,"network_type" bigint,"masquerade" boolean,"metric" bigint,"enabled" boolean,"groups" text,"access_control_groups" text,"skip_auto_apply" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_routes_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_routes_public_id" ON "routes" ("public_id");
CREATE INDEX IF NOT EXISTS "idx_routes_account_id" ON "routes" ("account_id");
CREATE TABLE "name_server_groups" ("id" text,"account_id" text,"public_id" text,"name" text,"description" text,"name_servers" text,"groups" text,"primary" boolean,"domains" text,"enabled" boolean,"search_domains_enabled" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_name_server_groups_g" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_name_server_groups_account_id" ON "name_server_groups" ("account_id");
CREATE TABLE "installations" ("id" bigserial,"installation_id_value" text,PRIMARY KEY ("id"));
CREATE TABLE "extra_settings" ("peer_approval_enabled" boolean,"user_approval_required" boolean,"integrated_validator" text,"integrated_validator_groups" text);
CREATE TABLE "posture_checks" ("id" text,"name" text,"description" text,"account_id" text,"public_id" text,"checks" text,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_posture_checks" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_posture_checks_account_id" ON "posture_checks" ("account_id");
CREATE TABLE "network_addresses" ("net_ip" text,"mac" text);
CREATE TABLE "networks" ("id" text,"account_id" text,"public_id" text,"name" text,"description" text,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_networks" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_networks_account_id" ON "networks" ("account_id");
CREATE TABLE "network_routers" ("id" text,"network_id" text,"account_id" text,"public_id" text,"peer" text,"peer_groups" text,"masquerade" boolean,"metric" bigint,"enabled" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_network_routers" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_network_routers_account_id" ON "network_routers" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_network_routers_network_id" ON "network_routers" ("network_id");
CREATE TABLE "network_resources" ("id" text,"network_id" text,"account_id" text,"public_id" text,"name" text,"description" text,"type" text,"domain" text,"prefix" text,"enabled" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_network_resources" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_network_resources_account_id" ON "network_resources" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_network_resources_network_id" ON "network_resources" ("network_id");
CREATE INDEX IF NOT EXISTS "idx_network_resources_public_id" ON "network_resources" ("public_id");
CREATE TABLE "account_onboardings" ("account_id" text,"onboarding_flow_pending" boolean,"signup_form_pending" boolean,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("account_id"),CONSTRAINT "fk_accounts_onboarding" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE);
CREATE TABLE "jobs" ("id" text,"created_at" timestamptz,"completed_at" timestamptz,"triggered_by" text,"peer_id" text,"account_id" text,"status" varchar(50),"failed_reason" text,"workload_workload_type" varchar(50),"workload_parameters" json,"workload_result" json,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_jobs_peer_id" ON "jobs" ("peer_id");
CREATE INDEX IF NOT EXISTS "idx_jobs_triggered_by" ON "jobs" ("triggered_by");
CREATE INDEX IF NOT EXISTS "idx_jobs_type" ON "jobs" ("workload_workload_type");
CREATE INDEX IF NOT EXISTS "idx_jobs_status" ON "jobs" ("status");
CREATE INDEX IF NOT EXISTS "idx_jobs_account_id" ON "jobs" ("account_id");
CREATE TABLE "zones" ("id" text,"account_id" text,"name" text,"domain" text,"enabled" boolean,"enable_search_domain" boolean,"distribution_groups" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_zones_account_id" ON "zones" ("account_id");
CREATE TABLE "records" ("account_id" text,"zone_id" text,"id" text,"name" text,"type" text,"content" text,"ttl" bigint,PRIMARY KEY ("id"),CONSTRAINT "fk_zones_records" FOREIGN KEY ("zone_id") REFERENCES "zones"("id"));
CREATE INDEX IF NOT EXISTS "idx_records_zone_id" ON "records" ("zone_id");
CREATE INDEX IF NOT EXISTS "idx_records_account_id" ON "records" ("account_id");
CREATE TABLE "user_invites" ("id" text,"account_id" text NOT NULL,"email" text NOT NULL,"name" text NOT NULL,"role" text NOT NULL,"auto_groups" text,"hashed_token" text NOT NULL,"expires_at" timestamptz NOT NULL,"created_at" timestamptz NOT NULL,"created_by" text NOT NULL,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_invites_email" ON "user_invites" ("email");
CREATE INDEX IF NOT EXISTS "idx_user_invites_account_id" ON "user_invites" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_user_invites_hashed_token" ON "user_invites" ("hashed_token");
CREATE TABLE "services" ("id" text,"account_id" text,"name" text,"domain" varchar(255),"proxy_cluster" text,"enabled" boolean,"terminated" boolean,"pass_host_header" boolean,"rewrite_redirects" boolean,"auth" text,"restrictions" text,"meta_created_at" timestamptz,"meta_certificate_issued_at" timestamptz,"meta_status" text,"meta_last_renewed_at" timestamptz,"session_private_key" text,"session_public_key" text,"source" text DEFAULT 'permanent',"source_peer" text,"mode" text DEFAULT 'http',"listen_port" integer,"port_auto_assigned" boolean,"private" boolean,"access_groups" text,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_services" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"));
CREATE INDEX IF NOT EXISTS "idx_service_source_peer" ON "services" ("source","source_peer");
CREATE INDEX IF NOT EXISTS "idx_services_proxy_cluster" ON "services" ("proxy_cluster");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_services_domain" ON "services" ("domain");
CREATE INDEX IF NOT EXISTS "idx_services_account_id" ON "services" ("account_id");
CREATE TABLE "targets" ("id" bigserial,"account_id" text NOT NULL,"service_id" text NOT NULL,"path" text,"host" text,"port" integer,"protocol" text,"target_id" text,"target_type" text,"enabled" boolean,"skip_tls_verify" boolean,"request_timeout" bigint,"session_idle_timeout" bigint,"path_rewrite" text,"custom_headers" text,"direct_upstream" boolean,"middlewares" text,"capture_max_request_bytes" bigint,"capture_max_response_bytes" bigint,"capture_content_types" text,"agent_network" boolean,"disable_access_log" boolean,"proxy_protocol" boolean,PRIMARY KEY ("id"),CONSTRAINT "fk_services_targets" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "idx_target_type" ON "targets" ("target_type");
CREATE INDEX IF NOT EXISTS "idx_target_id" ON "targets" ("target_id");
CREATE INDEX IF NOT EXISTS "idx_target_protocol" ON "targets" ("protocol");
CREATE INDEX IF NOT EXISTS "idx_target_port" ON "targets" ("port");
CREATE INDEX IF NOT EXISTS "idx_service_targets" ON "targets" ("service_id");
CREATE INDEX IF NOT EXISTS "idx_target_account" ON "targets" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_target_enabled" ON "targets" ("enabled");
CREATE TABLE "domains" ("id" text,"domain" text,"account_id" text,"target_cluster" text,"validated" boolean,"validation_expires_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "fk_accounts_domains" FOREIGN KEY ("account_id") REFERENCES "accounts"("id"),CONSTRAINT "uni_domains_id" UNIQUE ("id"),CONSTRAINT "uni_domains_domain" UNIQUE ("domain"));
CREATE INDEX IF NOT EXISTS "idx_domains_validation_expires_at" ON "domains" ("validation_expires_at");
CREATE INDEX IF NOT EXISTS "idx_domains_account_id" ON "domains" ("account_id");
CREATE TABLE "access_log_entries" ("id" text,"account_id" text,"service_id" text,"timestamp" timestamptz,"location_connection_ip" text,"location_country_code" text,"location_city_name" text,"location_geo_name_id" bigint,"subdivision_code" text,"method" text,"host" text,"path" text,"duration" bigint,"status_code" bigint,"reason" text,"user_id" text,"auth_method_used" text,"bytes_upload" bigint,"bytes_download" bigint,"protocol" text,"metadata" text,"agent_network" boolean,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_path" ON "access_log_entries" ("path");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_host" ON "access_log_entries" ("host");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_account_id" ON "access_log_entries" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_protocol" ON "access_log_entries" ("protocol");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_bytes_upload" ON "access_log_entries" ("bytes_upload");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_auth_method_used" ON "access_log_entries" ("auth_method_used");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_status_code" ON "access_log_entries" ("status_code");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_method" ON "access_log_entries" ("method");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_timestamp" ON "access_log_entries" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_service_id" ON "access_log_entries" ("service_id");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_agent_network" ON "access_log_entries" ("agent_network");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_bytes_download" ON "access_log_entries" ("bytes_download");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_user_id" ON "access_log_entries" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_access_log_entries_duration" ON "access_log_entries" ("duration");
CREATE TABLE "proxies" ("id" varchar(255),"session_id" varchar(36),"cluster_address" varchar(255) NOT NULL,"ip_address" varchar(45),"version" varchar(255),"account_id" varchar(255),"last_seen" timestamptz NOT NULL,"connected_at" timestamptz,"disconnected_at" timestamptz,"status" varchar(20) NOT NULL,"supports_custom_ports" boolean,"require_subdomain" boolean,"supports_crowdsec" boolean,"private" boolean,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_proxy_last_seen" ON "proxies" ("last_seen");
CREATE INDEX IF NOT EXISTS "idx_proxy_account_id" ON "proxies" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_proxy_cluster_status" ON "proxies" ("cluster_address","status");
CREATE TABLE "agent_network_providers" ("id" text,"account_id" text,"provider_id" text,"name" text,"upstream_url" text,"api_key" text,"extra_values" text,"models" text,"enabled" boolean,"skip_tls_verification" boolean,"metadata_disabled" boolean,"session_private_key" text,"session_public_key" text,"identity_header_user_id" text,"identity_header_groups" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_provider" ON "agent_network_providers" ("provider_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_providers_account_id" ON "agent_network_providers" ("account_id");
CREATE TABLE "agent_network_policies" ("id" text,"account_id" text,"name" text,"description" text,"enabled" boolean,"source_groups" text,"destination_provider_ids" text,"guardrail_ids" text,"limits" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_policies_account_id" ON "agent_network_policies" ("account_id");
CREATE TABLE "agent_network_guardrails" ("id" text,"account_id" text,"name" text,"description" text,"checks" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_guardrails_account_id" ON "agent_network_guardrails" ("account_id");
CREATE TABLE "agent_network_settings" ("account_id" text,"domain" varchar(255),"proxy_address" varchar(255),"enable_log_collection" boolean,"enable_prompt_collection" boolean,"redact_pii" boolean,"access_log_retention_days" bigint,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("account_id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_settings_proxy_address" ON "agent_network_settings" ("proxy_address");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_agent_network_settings_domain" ON "agent_network_settings" ("domain");
CREATE TABLE "agent_network_consumption" ("account_id" varchar(255),"dim_kind" varchar(16),"dim_id" varchar(255),"window_seconds" bigint,"window_start_utc" timestamptz,"tokens_input" bigint,"tokens_output" bigint,"cost_usd" decimal,"updated_at" timestamptz,PRIMARY KEY ("account_id","dim_kind","dim_id","window_seconds","window_start_utc"));
CREATE TABLE "agent_network_budget_rules" ("id" text,"account_id" text,"name" text,"enabled" boolean,"target_groups" text,"target_users" text,"limits" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_budget_rules_account_id" ON "agent_network_budget_rules" ("account_id");
CREATE TABLE "agent_network_access_log" ("id" text,"account_id" text,"service_id" text,"timestamp" timestamptz,"user_id" text,"source_ip" text,"method" text,"host" text,"path" text,"duration" bigint,"status_code" bigint,"auth_method" text,"bytes_upload" bigint,"bytes_download" bigint,"provider" text,"model" text,"session_id" text,"resolved_provider_id" text,"selected_policy_id" text,"decision" text,"deny_reason" text,"input_tokens" bigint,"output_tokens" bigint,"total_tokens" bigint,"cached_input_tokens" bigint,"cache_creation_tokens" bigint,"input_cost_usd" decimal NOT NULL DEFAULT 0,"cached_input_cost_usd" decimal NOT NULL DEFAULT 0,"cache_creation_cost_usd" decimal NOT NULL DEFAULT 0,"output_cost_usd" decimal NOT NULL DEFAULT 0,"stream" boolean,"request_prompt" text,"response_completion" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_provider" ON "agent_network_access_log" ("provider");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_user_id" ON "agent_network_access_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_anal_acct_session_ts" ON "agent_network_access_log" ("account_id","session_id","timestamp");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_account_id" ON "agent_network_access_log" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_selected_policy_id" ON "agent_network_access_log" ("selected_policy_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_session_id" ON "agent_network_access_log" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_status_code" ON "agent_network_access_log" ("status_code");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_timestamp" ON "agent_network_access_log" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_service_id" ON "agent_network_access_log" ("service_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_decision" ON "agent_network_access_log" ("decision");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_resolved_provider_id" ON "agent_network_access_log" ("resolved_provider_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_model" ON "agent_network_access_log" ("model");
CREATE TABLE "agent_network_access_log_group" ("log_id" text,"group_id" text,"account_id" text,PRIMARY KEY ("log_id","group_id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_group_group_id" ON "agent_network_access_log_group" ("group_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_access_log_group_account_id" ON "agent_network_access_log_group" ("account_id");
CREATE TABLE "agent_network_request_usage" ("id" text,"account_id" text,"timestamp" timestamptz,"user_id" text,"resolved_provider_id" text,"provider" text,"model" text,"session_id" text,"input_tokens" bigint,"output_tokens" bigint,"total_tokens" bigint,"cached_input_tokens" bigint,"cache_creation_tokens" bigint,"input_cost_usd" decimal NOT NULL DEFAULT 0,"cached_input_cost_usd" decimal NOT NULL DEFAULT 0,"cache_creation_cost_usd" decimal NOT NULL DEFAULT 0,"output_cost_usd" decimal NOT NULL DEFAULT 0,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_user_id" ON "agent_network_request_usage" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_timestamp" ON "agent_network_request_usage" ("timestamp");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_account_id" ON "agent_network_request_usage" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_session_id" ON "agent_network_request_usage" ("session_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_model" ON "agent_network_request_usage" ("model");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_resolved_provider_id" ON "agent_network_request_usage" ("resolved_provider_id");
CREATE TABLE "agent_network_request_usage_group" ("usage_id" text,"group_id" text,"account_id" text,PRIMARY KEY ("usage_id","group_id"));
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_group_account_id" ON "agent_network_request_usage_group" ("account_id");
CREATE INDEX IF NOT EXISTS "idx_agent_network_request_usage_group_group_id" ON "agent_network_request_usage_group" ("group_id");
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_ip ON peers (account_id, ip);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_dnslabel ON peers (account_id, dns_label);
CREATE UNIQUE INDEX IF NOT EXISTS idx_peers_key_unique ON peers (key);
