package handler

import (
	"encoding/json"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/magiconair/properties/assert"
	"github.com/wiretrustee/wiretrustee/management/server"
	"github.com/wiretrustee/wiretrustee/management/server/mock_server"
)

func initTestMetaData() *Peers {
	return &Peers{
		accountManager: &mock_server.MockAccountManager{
			GetAccountByUserOrAccountIdFunc: func(userId, accountId, domain string) (*server.Account, error) {
				return &server.Account{
					Id:     accountId,
					Domain: "hotmail.com",
					Peers: map[string]*server.Peer{
						"test_user": &server.Peer{
							Key:      "key",
							SetupKey: "setupkey",
							IP:       net.ParseIP("Test_IPv4"),
							Status:   &server.PeerStatus{},
							Name:     "PeerName",
							Meta: server.PeerSystemMeta{
								Hostname:  "hostname",
								GoOS:      "GoOS",
								Kernel:    "kernel",
								Core:      "core",
								Platform:  "platform",
								OS:        "OS",
								WtVersion: "development",
							},
						},
					},
				}, nil
			},
		},
		authAudience: "",
		jwtExtractor: JWTClaimsExtractor{
			extractClaimsFromRequestContext: func(r *http.Request, authAudiance string) JWTClaims {
				return JWTClaims{
					UserId:    "test_user",
					Domain:    "hotmail.com",
					AccountId: "test_id",
				}
			},
		},
	}
}

// Tests the GetPeers endpoint reachable in the route /api/peers
// Use the metadata generated by initTestMetaData() to check for values
func TestGetPeers(t *testing.T) {
	var tt = []struct {
		name           string
		expectedStatus int
		requestType    string
		requestPath    string
		requestBody    io.Reader
	}{
		{name: "GetPeersMetaData", requestType: http.MethodGet, requestPath: "/api/peers/", expectedStatus: http.StatusOK},
	}

	rr := httptest.NewRecorder()
	p := initTestMetaData()

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			req := httptest.NewRequest(tc.requestType, tc.requestPath, tc.requestBody)

			p.GetPeers(rr, req)

			res := rr.Result()
			defer res.Body.Close()

			if status := rr.Code; status != tc.expectedStatus {
				t.Fatalf("handler returned wrong status code: got %v want %v",
					status, http.StatusOK)
			}

			content, err := io.ReadAll(res.Body)
			if err != nil {
				t.Fatalf("I don't know what I expected; %v", err)
			}

			respBody := []*PeerResponse{}
			err = json.Unmarshal(content, &respBody)
			if err != nil {
				t.Fatalf("Sent content is not in correct json format; %v", err)
			}

			peer := respBody[0]
			assert.Equal(t, "PeerName", peer.Name)
			assert.Equal(t, "development", peer.Version)
			assert.Equal(t, net.ParseIP("Test_IPv4"), net.ParseIP(peer.IP))
			assert.Equal(t, "OS core", peer.OS)
		})
	}
}
