// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Update groups the RPCs that drive the enforced-update install flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetInstallerResult(): $CancellablePromise<$models.UpdateResult> {
    return $Call.ByID(2190725314).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Trigger(): $CancellablePromise<$models.UpdateResult> {
    return $Call.ByID(2415339649).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdateResult.createFrom;
