// Code generated by MockGen. DO NOT EDIT.
// Source: ./update_debouncer.go
//
// Generated by this command:
//
//	mockgen -source=./update_debouncer.go -destination=./update_debouncer_mock.go -package=grpc
//

// Package grpc is a generated GoMock package.
package grpc

import (
	reflect "reflect"
	time "time"

	network_map "github.com/netbirdio/netbird/management/internals/controllers/network_map"
	gomock "go.uber.org/mock/gomock"
)

// MockDebouncer is a mock of Debouncer interface.
type MockDebouncer struct {
	ctrl     *gomock.Controller
	recorder *MockDebouncerMockRecorder
	isgomock struct{}
}

// MockDebouncerMockRecorder is the mock recorder for MockDebouncer.
type MockDebouncerMockRecorder struct {
	mock *MockDebouncer
}

// NewMockDebouncer creates a new mock instance.
func NewMockDebouncer(ctrl *gomock.Controller) *MockDebouncer {
	mock := &MockDebouncer{ctrl: ctrl}
	mock.recorder = &MockDebouncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebouncer) EXPECT() *MockDebouncerMockRecorder {
	return m.recorder
}

// GetPendingUpdates mocks base method.
func (m *MockDebouncer) GetPendingUpdates() []*network_map.UpdateMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingUpdates")
	ret0, _ := ret[0].([]*network_map.UpdateMessage)
	return ret0
}

// GetPendingUpdates indicates an expected call of GetPendingUpdates.
func (mr *MockDebouncerMockRecorder) GetPendingUpdates() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingUpdates", reflect.TypeOf((*MockDebouncer)(nil).GetPendingUpdates))
}

// ProcessUpdate mocks base method.
func (m *MockDebouncer) ProcessUpdate(update *network_map.UpdateMessage) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessUpdate", update)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ProcessUpdate indicates an expected call of ProcessUpdate.
func (mr *MockDebouncerMockRecorder) ProcessUpdate(update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessUpdate", reflect.TypeOf((*MockDebouncer)(nil).ProcessUpdate), update)
}

// Stop mocks base method.
func (m *MockDebouncer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockDebouncerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDebouncer)(nil).Stop))
}

// TimerChannel mocks base method.
func (m *MockDebouncer) TimerChannel() <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimerChannel")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// TimerChannel indicates an expected call of TimerChannel.
func (mr *MockDebouncerMockRecorder) TimerChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimerChannel", reflect.TypeOf((*MockDebouncer)(nil).TimerChannel))
}
