//go:build integration

package networkmap_pgsql

import (
	"context"
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	networkmapdb "github.com/netbirdio/netbird/management/internals/network_map_db"
	"github.com/netbirdio/netbird/management/server/integrations/integrated_validator"
	"github.com/netbirdio/netbird/management/server/settings"
	"github.com/netbirdio/netbird/management/server/types"
	log "github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"go.uber.org/mock/gomock"
)

//go:embed network_map_data.sql
var nmapData string

//go:embed network_map_data_golden.json
var goldenNMap string

const EnvUpdateGoldenData = "NMAP_UPDATE_GOLDEN_DATA"

func TestGetNetworkMapData(t *testing.T) {
	ctx := context.TODO()

	// The two mocks are generated by different mock frameworks, so each needs a
	// controller of its own kind.
	extraSettingsManager := settings.NewMockManager(gomock.NewController(t))
	extraSettingsManager.EXPECT().GetExtraSettings(gomock.Any(), gomock.Any()).Return(&types.ExtraSettings{}, nil)

	peerValidators := integrated_validator.NewMockIntegratedValidator(gomock.NewController(t))
	peerValidators.EXPECT().GetValidatedPeers(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).Return(
		map[string]struct{}{
			"peer-id-1": {},
			"peer-id-2": {},
			"peer-id-3": {},
		}, nil)

	storeImpl := networkmapdb.NetworkMapDBStoreImpl{
		Store:                   store(t),
		ExtraSettingsManager:    extraSettingsManager,
		IntegratedPeerValidator: peerValidators,
	}

	for _, query := range strings.Split(nmapData, ";") {
		if err := store(t).Exec(ctx, query); err != nil {
			log.Fatalf("error initializing nmap test: %s", err.Error())
		}
	}

	nmap, err := storeImpl.GetNetworkMapData(ctx, "account-33")
	assert.NoError(t, err)

	serializedNMap, err := json.MarshalIndent(nmap, "", "  ")
	assert.NoError(t, err)

	if _, ok := os.LookupEnv(EnvUpdateGoldenData); ok {
		_, filename, _, _ := runtime.Caller(0)
		tosavepath := filepath.Join(filepath.Dir(filename), "network_map_data_golden.json")
		err = os.WriteFile(tosavepath, serializedNMap, 0644)
		assert.NoError(t, err)
		goldenNMap = string(serializedNMap)
	}
	assert.Equal(t, goldenNMap, string(serializedNMap))
}
