// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Connection groups the daemon RPCs that drive login / connect / disconnect.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Down(): $CancellablePromise<void> {
    return $Call.ByID(70044537);
}

export function Login(p: $models.LoginParams): $CancellablePromise<$models.LoginResult> {
    return $Call.ByID(252661358, p).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Logout(p: $models.LogoutParams): $CancellablePromise<void> {
    return $Call.ByID(3824847887, p);
}

/**
 * OpenURL launches the user's preferred browser to display url. Mirrors the
 * Fyne client's openURL helper so the SSO flow can pop the verification page
 * the same way as the legacy UI — WebKitGTK's window.open is blocked by the
 * embedded webview, and asking the user to copy/paste defeats the point of
 * SSO. Honors $BROWSER first, then falls back to the platform default.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3786555598, url);
}

export function Up(p: $models.UpParams): $CancellablePromise<void> {
    return $Call.ByID(3381092588, p);
}

export function WaitSSOLogin(p: $models.WaitSSOParams): $CancellablePromise<string> {
    return $Call.ByID(1751351500, p);
}

// Private type creation functions
const $$createType0 = $models.LoginResult.createFrom;
