// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Peers serves the dashboard data: one polled Status RPC and a long-running
 * SubscribeEvents stream that re-emits every event over the Wails event bus.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the current daemon status snapshot.
 */
export function Get(): $CancellablePromise<$models.Status> {
    return $Call.ByID(196038193).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Watch starts the background loops that feed the frontend:
 *   - statusStreamLoop: push-driven snapshots on connection-state change
 *     (Connected/Disconnected/Connecting, peer list, address). Drives the
 *     tray icon, Status page, and Peers page.
 *   - toastStreamLoop:   DNS / network / auth / connectivity / update
 *     SystemEvent stream. Drives OS notifications, the Recent Events
 *     list, and the update-overlay flag. The daemon-side RPC is named
 *     SubscribeEvents — only the loop's local alias differs to keep the
 *     two streams distinguishable in this file.
 * 
 * Safe to call once at boot; both loops self-restart on stream errors
 * via exponential backoff.
 */
export function Watch(): $CancellablePromise<void> {
    return $Call.ByID(741320382);
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
