# run process benchmarks on windows, macos, linux and freebsd in different workflows
name: "Run Process Benchmarks"
on:
  workflow_dispatch:
  push:
    branches:
      - optmize-process-check-time

jobs:
    run-benchmarks:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
              os: [ubuntu-latest, macos-latest]
              go-version: [1.23.x]
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
            cache: true

        - name: Run benchmarks
          run: sudo go test -bench=. -v ./client/system
    run-benchmarks-windows:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.23.x
            cache: true

        - run: go list -f '{{.GoFiles}}' ./client/system

        - name: Run benchmarks
          run: go test -bench . -v ./client/system
    run-benchmarks-freebsd:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - name: Test in FreeBSD
          id: test
          uses: vmactions/freebsd-vm@v1
          with:
            usesh: true
            copyback: false
            release: "14.2"
            prepare: |
              pkg install -y curl pkgconf xorg
              LATEST_VERSION=$(curl -s https://go.dev/VERSION?m=text|head -n 1)
              GO_TARBALL="$LATEST_VERSION.freebsd-amd64.tar.gz"
              GO_URL="https://go.dev/dl/$GO_TARBALL"
              curl -vLO "$GO_URL"
              tar -C /usr/local -vxzf "$GO_TARBALL"
            run: |
              set -e -x
              export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
              go test -bench=. -v ./client/system
